apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
  namespace: cronjob-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: batch-manager
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["create", "delete", "update", "patch", "list", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-manager-view
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: cronjob-manager
roleRef:
  kind: ClusterRole
  name: batch-manager
  apiGroup: rbac.authorization.k8s.io
